import "./globals.css";
import { MiniKitProvider } from "@worldcoin/minikit-js/minikit-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { JSX, ReactNode } from "react";
import { Navbar } from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "CHAT",
  description: "Generated by ARNNVV",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <MiniKitProvider>
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable,
          )}
        >
          <Navbar />
          {children}
          <Toaster richColors={true} />
        </body>
      </MiniKitProvider>
    </html>
  );
}
